# Generated by Django 5.2.17 on 2026-09-29 13:59

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        # Switch on PostgreSQL's pg_trgm extension (trigram similarity = typo tolerance).
        # Creating an extension needs a database user with enough rights (ours has them).
        TrigramExtension(),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('name', name='gin_trgm_ops'), name='product_name_trgm_idx'),
        ),
    ]
