"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read backend/.env into os.environ. Variables that already exist in the real
# environment (e.g. set by Docker Compose) win over values in the file.
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Read an environment variable as True/False ("true", "1", "yes", "on" count as True)."""
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    """Read a comma-separated environment variable as a list: "a, b" -> ['a', 'b']."""
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default on purpose: if it's missing, Django refuses to start (fail fast).
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a forgotten setting is the safe choice.
DEBUG = env_bool('DJANGO_DEBUG', False)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'django_filters',
    'corsheaders',
    # Our apps
    'accounts',
    'catalog',
    'cart',
    'orders',
]

MIDDLEWARE = [
    # Must be as high as possible, and before CommonMiddleware, so CORS headers are
    # added to every response (including errors and redirects) and preflight
    # OPTIONS requests are answered early.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # uses the psycopg (v3) driver
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            # Give up after 5 seconds instead of hanging when the database is down.
            'connect_timeout': 5,
        },
    }
}

# Use our own user model (accounts/models.py) instead of django.contrib.auth's User.
# Must be set BEFORE the first `migrate`.
AUTH_USER_MODEL = 'accounts.User'


# Django REST Framework
REST_FRAMEWORK = {
    # How DRF finds out WHO is making the request.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # "Authorization: Bearer <access token>" header: used by React and PowerShell.
        # Listed first, so a request without credentials gets 401 (not 403).
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # The browser session (after logging in to /admin/ or /api-auth/login/),
        # so the browsable API keeps working during development.
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Secure default: every endpoint requires a logged-in user unless the view
    # says otherwise (our catalog views use IsAdminOrReadOnly).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # List endpoints return pages: {"count", "next", "previous", "results"}.
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardPagination',
    # Query-parameter features available to every view that configures them
    # (filterset_class / search_fields / ordering_fields).
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'core.filters.StableOrderingFilter',
    ],
}

# CORS (django-cors-headers): which OTHER websites' JavaScript may call this API.
# The React dev server runs on http://localhost:5173. Comma-separated in .env.
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')

# Celery (background jobs). Redis is the "waiting line" for jobs.
# On Windows: redis://localhost:6379/0.  Inside Docker the worker uses redis://redis:6379/0.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_IGNORE_RESULT = True  # we don't need to store what tasks return

# Email. In development the "console" backend prints emails instead of sending them.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'ShopLite <orders@shoplite.local>')

# JSON Web Tokens (djangorestframework-simplejwt)
SIMPLE_JWT = {
    # Short-lived token sent with every API request.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '15'))),
    # Long-lived token used only to get new access tokens.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    # The word before the token in the header: "Authorization: Bearer <token>".
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Record the login time in User.last_login (visible in the admin).
    'UPDATE_LAST_LOGIN': True,
    # Our login serializer: lower-cases the email before checking the password.
    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.EmailTokenObtainPairSerializer',
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# While running the automated tests ("manage.py test"), use a fast password hasher.
# The real one is deliberately slow (to stop password guessing), which would make
# every test that creates a user slow too. Never used outside tests.
if len(sys.argv) > 1 and sys.argv[1] == 'test':
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# User-uploaded files (product images)
# MEDIA_ROOT: the folder on disk where uploads are saved.
# MEDIA_URL: the URL prefix they are served under (/media/products/2026/09/mug.jpg).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
