[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.6.3",
    "django>=5.2,<5.3",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.1",
    "djangorestframework>=3.17.2",
    "djangorestframework-simplejwt>=5.5.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.3",
]

# Settings for the "coverage" tool (which lines of our code the tests actually run).
[tool.coverage.run]
source = ["."]
omit = [".venv/*", "*/migrations/*", "*/tests.py", "core/testing.py", "manage.py", "config/asgi.py", "config/wsgi.py"]

[tool.coverage.report]
skip_empty = true
show_missing = true

[dependency-groups]
dev = [
    "coverage>=7.16.2",
]
