# Generated by Django 5.2.17 on 2026-09-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=50, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50)),
                ('amount', models.PositiveIntegerField(help_text='In the smallest unit of the currency (paise for INR).')),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('created', 'Waiting for payment'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='created', max_length=10)),
                ('confirmed_via', models.CharField(blank=True, choices=[('checkout', 'Checkout (browser)'), ('webhook', 'Webhook (Razorpay server)')], max_length=10)),
                ('error_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
